export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const TEACHER_ROUTE = '/teacher'
export const STUDENT_ROUTE = '/student'
export const ABOUT_ROUTE = '/about'
export const COURSE_ROUTE = '/course'